version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536 
    mem_limit: 2g
  logstash:
    image: logstash:6.5.4
    environment:
      - path.config=null
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logs:/logs:ro
    container_name: logstash
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    restart: always
    mem_limit: 1g
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:6.5.4
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    restart: always
    mem_limit: 512m
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
